import type { Metadata } from "next";
import "./styles/globals.css";
import Layout from "./page-components/structure/Layout";
import CustomCursor from "./page-components/CustomCursor";

export const metadata: Metadata = {
  title: "ProdCollab Design System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomCursor fill="black" />
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}